package com.example.metroid_prototype.helpers;

public enum PlayerState {
    RUN_RIGHT,
    RUN_LEFT,
    IDLE_RIGHT,
    IDLE_LEFT,
    DUCK_RIGHT,
    DUCK_LEFT,
    ROLL_RIGHT,
    ROLL_LEFT,
    ABOUT_TO_STAND_RIGHT,
    ABOUT_TO_STAND_LEFT,
    SOMERSAULT_RIGHT,
    SOMERSAULT_LEFT,
    JUMPING_RIGHT,
    JUMPING_LEFT,
    FALLING_RIGHT,
    FALLING_LEFT,
    SHOOTING_RUN_RIGHT,
    SHOOTING_RUN_LEFT,
    SHOOTING_FALL_RIGHT,
    SHOOTING_FALL_LEFT,
    SHOOTING_IDLE_RIGHT,
    SHOOTING_IDLE_LEFT,
    SHOOTING_JUMP_RIGHT,
    SHOOTING_JUMP_LEFT
}
